#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Intune.Android.Resource", IsApplication=true)]

namespace Intune.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int accountNameTextView = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int accountsListView = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int atUserNameEditText = 2131165203;
			
			// aapt resource value: 0x7f070002
			public const int balanceTextView = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int buttonSignIn = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int editEmail = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int editPassword = 2131165192;
			
			// aapt resource value: 0x7f07000f
			public const int emailEditText = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int fullNameEditText = 2131165201;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout2 = 2131165194;
			
			// aapt resource value: 0x7f070017
			public const int login_menu_forgot = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int login_menu_register = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int menu_comment = 2131165211;
			
			// aapt resource value: 0x7f070019
			public const int menu_contacts = 2131165209;
			
			// aapt resource value: 0x7f07001e
			public const int menu_new = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int menu_open = 2131165213;
			
			// aapt resource value: 0x7f07001a
			public const int menu_refresh = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int menu_share_account = 2131165212;
			
			// aapt resource value: 0x7f070012
			public const int mobileEditText = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int okButton = 2131165205;
			
			// aapt resource value: 0x7f070010
			public const int passwordEditText = 2131165200;
			
			// aapt resource value: 0x7f070016
			public const int resultTextView = 2131165206;
			
			// aapt resource value: 0x7f070009
			public const int space1 = 2131165193;
			
			// aapt resource value: 0x7f070014
			public const int space2 = 2131165204;
			
			// aapt resource value: 0x7f070003
			public const int space3 = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int space4 = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int space5 = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int textViewResult = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int textViewTitle = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccountListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Register = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int login_mennus = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int main_mennus = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int IntuneTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
